version: '3'

services:
  wordpress:
    build:
      context: .
      dockerfile: ./.docker/wordpress/Dockerfile
      args:
        - HOST_UID=${HOST_UID}
    stop_signal: SIGINT
    env_file: .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "80:8000"
    volumes:
      - ./wordpress:/var/www/html
    depends_on:
      db:
        condition: service_healthy
    command: ["php", "-S", "0.0.0.0:8000"]

  db:
    image: mysql:8.0
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 5s
      retries: 10
    command: '--default-authentication-plugin=mysql_native_password'


  phpmyadmin:
    image: phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: ${MYSQL_USERNAME}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
      UPLOAD_LIMIT: 300M
    volumes:
      - phpmyadmindata:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      db:
        condition: service_healthy

  mailpit:
    image: 'axllent/mailpit:latest'
    ports:
        - '1025:1025'
        - '8025:8025'

volumes:
  db_data:
  phpmyadmindata: